## Travis CI Integration
language: csharp

matrix:
  include:
    - os: linux
      dist: trusty
      mono: latest
      dotnet: 2.1.0
    - os: osx
      osx_image: xcode10
      mono: latest
      dotnet: 2.1.0

script:
  - ./build.sh --target=Travis --verbosity=diagnostic
